### PR TITLE
Chore/change to bitbar api v2

### PR DESCRIPTION
**Pull request by jussikuosa**
Fix a few missing things from Bitbar changes.

### CODE REVIEW

**Comment by jussikuosa** [comment]
These changes are manually tested on my laptop with @iglunev

**Review by jussikuosa — COMMENTED** [review]
Looks good, is the -b switch ok?

**Comment by iglunev** [comment]
Changed the -b switch to -w

**Review by ujappelbe — APPROVED** [review]
LGTM 👍 Did not actually run code

**Review by iglunev — APPROVED** [review]
Looks good, works on CI

**Pull request merged**
