### PR TITLE
New API endpoints - compatibility

### PR DESCRIPTION
**Pull request by szprutamich**

### CODE REVIEW

**Comment by szprutamich** [comment]
Option -l - prints available device groups and frameworks
Options:
-b - framework - specify framework to be used in tests (required)
-o - osType - specify osType of the run (same as framework's osType and device group's osType etc.)

Example:
 -b 339 -o "ANDROID"

**Comment by jussikuosa** [comment]
NVM - this was an RTM error... 
Now I get the following error: 
```
./testdroid_cmdline.sh -u "$TD_API_KEY" \
                        -t "UnityAds_android" \
                        -a "`pwd`/../../lib/build/outputs/apk/androidTest.apk" \
                        -r "JUSSI KUOSA TEST" \
                        -d "23250" \
                        -c "SINGLE" \
                        -z "`pwd`/../testfolder" \
                        -v  -o "ANDROID" -b 541
...
+++ curl -H 'Accept: application/json' -u XXXXXXX: -POST -H 'Content-Type: application/json' --data '{"testRunName":"JUSSI KUOSA TEST","osType":"ANDROID","frameworkId":"541","projectId":"199369934","timeout":"600","scheduler":"SINGLE","deviceGroupId":"23250","maxAutoRetriesCount":"","files":[{"id":"127506325"},{"id":"127507764"}]}' https://cloud.bitbar.com/api/v2/me/runs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   317    0    86  100   231     76    206  0:00:01  0:00:01 --:--:--   206
++ response='{"message":"Framework requires application file with extension: apk","statusCode":400}'
+++ echo '{"message":"Framework requires application file with extension: apk","statusCode":400}'
+++ jq .id
++ test_run_id=null

```

**Comment by szprutamich** [comment]
I guess the file androidTest.apk is not an android application but some tests. 
Btw be careful with posting api key here. The repo is public. I recommend resetting it.

**Comment by jussikuosa** [comment]
Thanks @szprutamich - I'll double-check the apk and thanks for spotting the plain api key! I forgot to hide it when I edited my comment :-( We'll rotate the key today still.

**Comment by szprutamich** [comment]
Any further issues? ;)

**Comment by jussikuosa** [comment]
We tweaked a few things still and opened https://github.com/Applifier/bitbar-ssa-client/pull/34 so I'm closing this one.

**Pull request closed without merging**
